### PR TITLE
fix: remove the auto generated selectors for job

### LINKED ISSUE #456: [BUG] Jobs can't be propagate to member clusters
### **Describe the bug**
During my testing, I encountered an error when Fleet Manager tried to distribute Jobs to Member Clusters as below:
```
message: 'Failed to apply manifest: Job.batch 'hello-world-job' is invalid:
          [spec.template.metadata.labels[controller-uid]: Invalid value: map[string]string{'controller-uid':'91cb485c-9966-401a-b68e-2a1d3ffc1c98',
          'job-name':'hello-world-job'}: must be ''f81acbaf-b289-465d-923f-f022f6cf77bf'',
          spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{'controller-uid':'91cb485c-9966-401a-b68e-2a1d3ffc1c98'},
          MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` not auto-generated]'
        reason: appliedManifestFailed
        status: 'False'
```

### **Environment**
Please provide the following: 
- Hub cluster details
- Member cluster details

### **To Reproduce**
```
apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  completions: 20
  parallelism: 5
  template:
    spec:
      containers:
      - name: hello-world
        image: busybox
        command: ["sh", "-c", "echo 'Hello, World!'"]
      restartPolicy: Never
```

### **Expected behavior**
Should see the job in the member clusters

### PR DESCRIPTION
**Pull request by ryanzhang-oss**
### Description of your changes

K8s api auto generated some [selector](https://github.com/kubernetes/kubernetes/blob/d4fde1e92a83cb533ae63b3abe9d49f08efb7a2f/pkg/registry/batch/job/strategy.go#L219)  for job based on the jobs' uid before it persist that will not work on the member cluster since its uid will change.

Fixes #456

I have:

- [x] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

UT

### CODE REVIEW

File: pkg/controllers/clusterresourceplacement/resource_selector.go [hunk 1]
```diff
@@ -353,6 +354,14 @@ func generateRawContent(object *unstructured.Unstructured) ([]byte, error) {
 		if err != nil {
 			return nil, fmt.Errorf("failed to get the ports field in Serivce object, name =%s: %w", object.GetName(), err)
 		}
+	} else if object.GetKind() == "Job" && object.GetAPIVersion() == batchv1.SchemeGroupVersion.String() {
+		if manualSelector, exist, _ := unstructured.NestedString(object.Object, "spec", "manualSelector"); !exist || manualSelector == "true" {
```
Comment (michaelawyu) [inline pkg/controllers/clusterresourceplacement/resource_selector.go:358]: Hi Ryan! This should be `!exist || manualSelector == "false"`, right? If the `manualSelector` is `true`, the customer has its own `.spec.selector` specified and we shouldn't clear the value.

File: pkg/controllers/clusterresourceplacement/resource_selector.go [hunk 2]
```diff
@@ -353,6 +354,14 @@ func generateRawContent(object *unstructured.Unstructured) ([]byte, error) {
...
+			// remove the selector field added by the api-server if the job is not created with manual selector
+			// https://github.com/kubernetes/kubernetes/blob/d4fde1e92a83cb533ae63b3abe9d49f08efb7a2f/pkg/registry/batch/job/strategy.go#L219
+			unstructured.RemoveNestedField(object.Object, "spec", "selector")
+			unstructured.RemoveNestedField(object.Object, "spec", "template", "metadata", "creationTimestamp")
+			unstructured.RemoveNestedField(object.Object, "spec", "template", "metadata", "labels")
```
Comment (michaelawyu) [inline pkg/controllers/clusterresourceplacement/resource_selector.go:363]: This clears out all the labels on the pod template, not just the UID label set by the system, which could have some side effects on the user-side, e.g. the user may still want all the child pods to have some labels that are not used for job selectors -> though I am not 100% sure how many users would have such labels

Comment (zhiying-lin) [reply pkg/controllers/clusterresourceplacement/resource_selector.go:363]: echo chen's comment. Can we only clear the the controller-uid  when its value = the job uuid? same for the  job-name.

File: pkg/controllers/clusterresourceplacement/resource_selector.go [hunk 3]
```diff
@@ -353,6 +354,17 @@ func generateRawContent(object *unstructured.Unstructured) ([]byte, error) {
 		if err != nil {
 			return nil, fmt.Errorf("failed to get the ports field in Serivce object, name =%s: %w", object.GetName(), err)
 		}
+	} else if object.GetKind() == "Job" && object.GetAPIVersion() == batchv1.SchemeGroupVersion.String() {
+		if manualSelector, exist, _ := unstructured.NestedBool(object.Object, "spec", "manualSelector"); !exist || !manualSelector {
+			// remove the selector field added by the api-server if the job is not created with manual selector
```
Comment (zhiying-lin) [inline pkg/controllers/clusterresourceplacement/resource_selector.go:359]:
```suggestion
			// remove the selector field and labels added by the api-server if the job is not created with manual selector
			// whose value conflict with the ones created by the member cluster api server
```

**Review by zhiying-lin — APPROVED** [review]
one minor comment, others LTGM
